# Generated by Django 4.2.7 on 2023-11-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavete', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
