# Generated by Django 4.2.7 on 2023-11-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile_about_alter_userprofile_avatar'),
        ('kavete', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile'),
        ),
    ]
