# Generated by Django 4.2.7 on 2023-11-22 18:44

from django.db import migrations, models
import user_profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_profiles.models.unique_avatar_name),
        ),
    ]
